# Generated by Django 2.0 on 2020-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_case',
            name='affiliation',
            field=models.CharField(choices=[(('Zanu PF', 'Zanu PF'), ('MDC', 'MDC'))], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='t_case',
            name='program',
            field=models.CharField(choices=[('Farm Mechanisation Scheme', 'Farm Mechanisation Scheme')], default='', max_length=50),
        ),
    ]
