# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-23 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('libs', '0003_auto_20200719_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
