# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('libs', '0004_auto_20200723_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_case',
            name='id',
        ),
        migrations.AddField(
            model_name='t_case',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='libs_t_case', serialize=False, to='cms.CMSPlugin'),
            preserve_default=False,
        ),
    ]
